module.exports = {
  ClasificacionDensidadPlantacionRepository: require('./clasificaciondensidadplantacion.repository'),
  ComunaMasterRepository: require('./comunamaster.repository'),
  EstadoRepository: require('./estado.repository'),
  PaisMasterRepository: require('./paismaster.repository'),
  EspecieMasterRepository: require('./especiemaster.repository'),
  RegionMasterRepository: require('./region-master.repository'),
  SexoRepository: require('./sexo.repository'),
  TipoCoberturaRepository: require('./tipo-cobertura.repository'),
  TipoEquipoRepository: require('./tipo-equipo.repository'),
  VariedadMasterRepository: require('./variedad-master.repository'),
  EstadoCivilRepository: require('./estado-civil.repository'),
  RelacionFamiliarRepository: require('./relacion-familiar.repository'),
  TipoCargaFamiliarRepository: require('./tipo-carga-familiar.repository'),
  UnidadRepository: require('./unidad.repository'),
  FuncionalidadRepository: require('./funcionalidad.repository'),
  ProductorRepository: require('./productor.repository'),
  UserRepository: require('./user.repository'),
  TipoRecoleccionRepository: require('./tipo-recoleccion.repository'),
  UnidadMedidaRepository: require('./unidad-medida.repository'),  
  BancoRepository: require('./banco.repository'),
};
