module.exports = {
  ClasificacionDensidadPlantacionController: require('./clasificaciondensidadplantacion.controller'),
  ComunaMasterController: require('./comunamaster.controller'),
  EspecieMasterController: require('./especiemaster.controller'),
  EstadoController: require('./estado.controller'),
  PaisMasterController: require('./paismaster.controller'),
  RegionMasterController: require('./region-master.controller'),
  SexoController: require('./sexo.controller'),
  TipoCoberturaController: require('./tipo-cobertura.controller'),
  TipoEquipoController: require('./tipo-equipo.controller'),
  VariedadMasterController: require('./variedad-master.controller'),
  EstadoCivilController: require('./estado-civil.controller'),
  RelacionFamiliarController: require('./relacion-familiar.controller'),
  TipoCargaFamiliarController: require('./tipo-carga-familiar.controller'),
  UnidadController: require('./unidad.controller'),
  FuncionalidadController: require('./funcionalidad.controller'),
  ProductorController: require('./productor.controller'),
  UserController: require('./user.controller'),
  TipoRecoleccionController: require('./tipo-recoleccion.controller'),
  UnidadMedidaController: require('./unidad-medida.controller'),
  BancoController: require('./banco.controller'),
};