module.exports = {
  ClasificacionDensidadRoute: require('./clasificaciondensidadplantacion.route'),
  ComunaMasterRoute: require('./comunamaster.route'),
  EspecieMasterRoute: require('./especiemaster.route'),
  EstadoRoute: require('./estado.route'),
  PaisMasterRoute: require('./paismaster.route'),
  RegionMasterRoute: require('./region-master.route'),
  SexoRoute: require('./sexo.route'),
  TipoCoberturaRoute: require('./tipo-cobertura.route'),
  TipoEquipoRoute: require('./tipo-equipo.route'),
  VariedadMasterRoute: require('./variedad-master.route'),
  EstadoCivilRoute: require('./estado-civil.route'),
  RelacionFamiliarRoute: require('./relacion-familiar.route'),
  TipoCargaFamiliarRoute: require('./tipo-carga-familiar.route'),
  UnidadRoute: require('./unidad.route'),
  FuncionalidadRoute: require('./funcionalidad.route'),
  ProductorRoute: require('./productor.route'),
  UserRoute: require('./user.route'),
  TipoRecoleccionRoutes: require('./tipo-recoleccion.route'),
  UnidadMedidaRoutes: require('./unidad-medida.route'),
  BancoRoutes: require('./banco.route'),
};