module.exports = {
  ClasificacionDensidadPlantacionService: require('./clasificaciondensidadplantacion.service'),
  ComunaMasterService: require('./comunamaster.service'),
  EspecieMasterService: require('./especiemaster.service'),
  EstadoService: require('./estado.service'),
  PaisMasterService: require('./paismaster.service'),
  RegionMasterService: require('./region-master.service'),
  SexoService: require('./sexo.service'),
  TipoCoberturaService: require('./tipo-cobertura.service'),
  TipoEquipoService: require('./tipo-equipo.service'),
  VariedadMasterService: require('./variedad-master.service'),
  EstadoCivilService: require('./estado-civil.service'),
  RelacionFamiliarService: require('./relacion-familiar.service'),
  TipoCargaFamiliarService: require('./tipo-carga-familiar.service'),
  UnidadService: require('./unidad.service'),
  FuncionalidadService: require('./funcionalidad.service'),
  ProductorService: require('./productor.service'),
  UserService: require('./user.service'),
  TipoRecoleccionService: require('./tipo-recoleccion.service'),
  UnidadMedidaService: require('./unidad-medida.service'),
  BancoService: require('./banco.service'),
};
